Repository openjdk/riscv-port-jdk17u, pull requests merged in 2023-03, with the labels that each got.

#3 8290164: compiler/runtime/TestConstantsInError.java fails on riscv
  test/hotspot/jtreg/compiler/runtime/TestConstantsInError.java
Labels: rfr, backport

#4 8293100: RISC-V: Need to save and restore callee-saved FloatRegisters in StubGenerator::generate_call_stub
  src/hotspot/cpu/riscv/frame_riscv.hpp
  src/hotspot/cpu/riscv/riscv.ad
  src/hotspot/cpu/riscv/stubGenerator_riscv.cpp
  src/hotspot/cpu/riscv/vmreg_riscv.cpp
Labels: ready, rfr, backport, clean

#5 8285437: riscv: Fix MachNode size mismatch for MacroAssembler::verify_oops*
  src/hotspot/cpu/riscv/macroAssembler_riscv.cpp
Labels: ready, rfr, backport, clean

#6 8294083: RISC-V: Minimal build failed with --disable-precompiled-headers
  src/hotspot/cpu/riscv/c1_Runtime1_riscv.cpp
  src/hotspot/cpu/riscv/macroAssembler_riscv.cpp
  src/hotspot/cpu/riscv/nativeInst_riscv.cpp
  src/hotspot/cpu/riscv/templateInterpreterGenerator_riscv.cpp
Labels: rfr, backport

#8 8296771: RISC-V: C2: assert(false) failed: bad AD file
  src/hotspot/cpu/riscv/riscv.ad
Labels: ready, rfr, backport, clean

#11 8287970: riscv: jdk/incubator/vector/*VectorTests failing
  src/hotspot/cpu/riscv/riscv_v.ad
Labels: rfr, backport

#10 8295926: RISC-V: C1: Fix LIRGenerator::do_LibmIntrinsic
  src/hotspot/cpu/riscv/c1_LIRGenerator_riscv.cpp
  test/hotspot/jtreg/compiler/floatingpoint/TestLibmIntrinsics.java
Labels: ready, rfr, backport, clean

#12 8296448: RISC-V: Fix temp usages of heapbase register killed by MacroAssembler::en/decode_klass_not_null
  src/hotspot/cpu/riscv/c1_LIRAssembler_riscv.cpp
  src/hotspot/cpu/riscv/c1_MacroAssembler_riscv.cpp
  src/hotspot/cpu/riscv/macroAssembler_riscv.cpp
  src/hotspot/cpu/riscv/macroAssembler_riscv.hpp
  src/hotspot/cpu/riscv/methodHandles_riscv.cpp
  src/hotspot/cpu/riscv/riscv.ad
  src/hotspot/cpu/riscv/sharedRuntime_riscv.cpp
  src/hotspot/cpu/riscv/stubGenerator_riscv.cpp
Labels: rfr, backport

#16 8287425: Remove unnecessary register push for MacroAssembler::check_klass_subtype_slow_path
  src/hotspot/cpu/riscv/macroAssembler_riscv.cpp
Labels: rfr, backport

#14 8294087: RISC-V: RVC: Fix a potential alignment issue and add more alignment assertions for the patchable calls/nops
  src/hotspot/cpu/riscv/c1_LIRAssembler_riscv.cpp
  src/hotspot/cpu/riscv/c1_MacroAssembler_riscv.cpp
  src/hotspot/cpu/riscv/gc/shared/barrierSetAssembler_riscv.cpp
  src/hotspot/cpu/riscv/macroAssembler_riscv.cpp
  src/hotspot/cpu/riscv/macroAssembler_riscv.hpp
  src/hotspot/cpu/riscv/nativeInst_riscv.cpp
  src/hotspot/cpu/riscv/riscv.ad
  src/hotspot/cpu/riscv/sharedRuntime_riscv.cpp
Labels: rfr, backport

#15 8291947: riscv: fail to build after JDK-8290840
  src/hotspot/cpu/riscv/icache_riscv.cpp
  src/hotspot/os_cpu/linux_riscv/os_linux_riscv.hpp
Labels: ready, rfr, backport

#13 8291893: riscv: remove fence.i used in user space
  src/hotspot/cpu/riscv/assembler_riscv.cpp
  src/hotspot/cpu/riscv/assembler_riscv.hpp
  src/hotspot/cpu/riscv/compiledIC_riscv.cpp
  src/hotspot/cpu/riscv/globals_riscv.hpp
  src/hotspot/cpu/riscv/icache_riscv.cpp
  src/hotspot/cpu/riscv/macroAssembler_riscv.cpp
  src/hotspot/cpu/riscv/macroAssembler_riscv.hpp
  src/hotspot/cpu/riscv/nativeInst_riscv.hpp
  src/hotspot/cpu/riscv/sharedRuntime_riscv.cpp
  src/hotspot/os_cpu/linux_riscv/orderAccess_linux_riscv.hpp
Labels: ready, rfr, backport

#9 8296602: RISC-V: improve performance of copy_memory stub
  src/hotspot/cpu/riscv/stubGenerator_riscv.cpp
Labels: ready, rfr, backport, clean

#19 8304293: RISC-V: JDK-8276799 missed atomic intrinsic support for C1
  src/hotspot/cpu/riscv/vm_version_riscv.cpp
Labels: ready, rfr, backport, clean

#20 8285711: riscv: RVC: Support disassembler show-bytes option
  src/hotspot/cpu/riscv/assembler_riscv.hpp
Labels: ready, rfr, backport, clean

#22 8297644: RISC-V: Compilation error when shenandoah is disabled
  src/hotspot/cpu/riscv/riscv.ad
Labels: ready, rfr, backport, clean

#21 8285699: riscv: Provide information when hitting a HaltNode
  src/hotspot/cpu/riscv/assembler_riscv.hpp
  src/hotspot/cpu/riscv/frame_riscv.hpp
  src/hotspot/cpu/riscv/macroAssembler_riscv.cpp
  src/hotspot/cpu/riscv/macroAssembler_riscv.hpp
  src/hotspot/cpu/riscv/nativeInst_riscv.cpp
  src/hotspot/cpu/riscv/riscv.ad
  src/hotspot/cpu/riscv/stubGenerator_riscv.cpp
  src/hotspot/cpu/riscv/templateInterpreterGenerator_riscv.cpp
  src/hotspot/os_cpu/linux_riscv/os_linux_riscv.cpp
Labels: rfr, backport

#23 8294086: RISC-V: Cleanup InstructionMark usages in the backend
  src/hotspot/cpu/riscv/assembler_riscv.hpp
  src/hotspot/cpu/riscv/macroAssembler_riscv.cpp
  src/hotspot/cpu/riscv/macroAssembler_riscv.hpp
Labels: ready, rfr, backport, clean

#24 8294187: RISC-V: Unify all relocations for the backend into AbstractAssembler::relocate()
  src/hotspot/cpu/riscv/assembler_riscv.cpp
  src/hotspot/cpu/riscv/assembler_riscv.hpp
  src/hotspot/cpu/riscv/c1_CodeStubs_riscv.cpp
  src/hotspot/cpu/riscv/c1_LIRAssembler_riscv.cpp
  src/hotspot/cpu/riscv/c1_LIRAssembler_riscv.hpp
  src/hotspot/cpu/riscv/c2_safepointPollStubTable_riscv.cpp
  src/hotspot/cpu/riscv/macroAssembler_riscv.cpp
Labels: ready, rfr, backport, clean

#26 8297715: RISC-V: C2: Use single-bit instructions from the Zbs extension
  src/hotspot/cpu/riscv/assembler_riscv.hpp
  src/hotspot/cpu/riscv/globals_riscv.hpp
  src/hotspot/cpu/riscv/riscv.ad
  src/hotspot/cpu/riscv/riscv_b.ad
Labels: ready, rfr, backport

#25 8300109: RISC-V: Improve code generation for MinI/MaxI nodes
  src/hotspot/cpu/riscv/riscv.ad
Labels: ready, rfr, backport, clean

#28 8294366: RISC-V: Partially mark out incompressible regions
  src/hotspot/cpu/riscv/assembler_riscv.hpp
  src/hotspot/cpu/riscv/c1_MacroAssembler_riscv.cpp
  src/hotspot/cpu/riscv/gc/shared/barrierSetAssembler_riscv.cpp
  src/hotspot/cpu/riscv/macroAssembler_riscv.cpp
  src/hotspot/cpu/riscv/nativeInst_riscv.cpp
  src/hotspot/cpu/riscv/riscv.ad
  src/hotspot/cpu/riscv/sharedRuntime_riscv.cpp
Labels: rfr, backport

#30 8305112: RISC-V: Typo fix for RVC description
  src/hotspot/cpu/riscv/assembler_riscv.hpp
Labels: ready, rfr, backport, clean

#29 8295110: RISC-V: Mark out relocations as incompressible
  src/hotspot/cpu/riscv/assembler_riscv.cpp
  src/hotspot/cpu/riscv/assembler_riscv.hpp
  src/hotspot/cpu/riscv/c1_CodeStubs_riscv.cpp
  src/hotspot/cpu/riscv/c1_LIRAssembler_riscv.cpp
  src/hotspot/cpu/riscv/c1_Runtime1_riscv.cpp
  src/hotspot/cpu/riscv/c2_safepointPollStubTable_riscv.cpp
  src/hotspot/cpu/riscv/gc/z/zBarrierSetAssembler_riscv.cpp
  src/hotspot/cpu/riscv/interp_masm_riscv.cpp
  src/hotspot/cpu/riscv/jniFastGetField_riscv.cpp
  src/hotspot/cpu/riscv/macroAssembler_riscv.cpp
  src/hotspot/cpu/riscv/macroAssembler_riscv.hpp
  src/hotspot/cpu/riscv/sharedRuntime_riscv.cpp
  src/hotspot/cpu/riscv/templateTable_riscv.cpp
Labels: rfr, backport

#31 8295396: RISC-V: Cleanup useless CompressibleRegions
  src/hotspot/cpu/riscv/macroAssembler_riscv.cpp
  src/hotspot/cpu/riscv/riscv.ad
Labels: ready, rfr, backport, clean

#32 8299168: RISC-V: Fix MachNode size mismatch for MacroAssembler::_verify_oops*
  src/hotspot/cpu/riscv/macroAssembler_riscv.cpp
Labels: rfr, backport
