Repository openjdk/riscv-port-jdk17u, pull requests merged in 2023-04, with the labels that each got.

#33 8305512: RISC-V: Enable RVC extension by default on supported hardware
  src/hotspot/cpu/riscv/globals_riscv.hpp
Labels: rfr

#34 8290137: riscv: small refactoring for add_memory_int32/64
  src/hotspot/cpu/riscv/assembler_riscv.cpp
  src/hotspot/cpu/riscv/assembler_riscv.hpp
  src/hotspot/cpu/riscv/c1_CodeStubs_riscv.cpp
  src/hotspot/cpu/riscv/c1_LIRAssembler_arraycopy_riscv.cpp
  src/hotspot/cpu/riscv/c1_LIRAssembler_riscv.cpp
  src/hotspot/cpu/riscv/macroAssembler_riscv.cpp
  src/hotspot/cpu/riscv/macroAssembler_riscv.hpp
  src/hotspot/cpu/riscv/vtableStubs_riscv.cpp
Labels: ready, rfr, backport, clean

#35 8293474: RISC-V: Unify the way of moving function pointer
  src/hotspot/cpu/riscv/gc/shenandoah/shenandoahBarrierSetAssembler_riscv.cpp
  src/hotspot/cpu/riscv/macroAssembler_riscv.cpp
  src/hotspot/cpu/riscv/macroAssembler_riscv.hpp
Labels: rfr, backport

#36 8294430: RISC-V: Small refactoring for movptr_with_offset
  src/hotspot/cpu/riscv/assembler_riscv.cpp
  src/hotspot/cpu/riscv/assembler_riscv.hpp
  src/hotspot/cpu/riscv/gc/shared/barrierSetAssembler_riscv.cpp
  src/hotspot/cpu/riscv/gc/shared/barrierSetNMethod_riscv.cpp
  src/hotspot/cpu/riscv/macroAssembler_riscv.cpp
  src/hotspot/cpu/riscv/nativeInst_riscv.cpp
  src/hotspot/cpu/riscv/nativeInst_riscv.hpp
  src/hotspot/cpu/riscv/stubGenerator_riscv.cpp
  src/hotspot/cpu/riscv/templateTable_riscv.cpp
Labels: rfr, backport
